layout: sidebar
style: dark

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 
  exclude:
    archived: false
    forks: false
    projects: lantaoyu.github.io , personal-website , dkanzariya.github.io
    # lantaoyu.github.io
    #personal-website

social_media: 
  twitter: dkanzariyaa
  linkedin: dharmesh-kanzariya-a32b1917b
  medium: dkanzariya
  instagram: dkanzariya
  
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: dkanzariyaa
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Hello World
    web_url: https://medium.com/@dkanzariya/hello-world-2cb8fba2b1aa
    image_url: https://miro.medium.com/max/2835/0*psLS-hA0H2zh9iYt