layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 
  exclude:
    archived: false
    forks: false
    projects: lantaoyu.github.io , personal-website , dkanzariya.github.io
    # lantaoyu.github.io
    #personal-website

social_media: 
  twitter: dkanzariyaa
  linkedin: dharmesh-kanzariya-a32b1917b
  medium: dkanzariya
  instagram: dkanzariya
  
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: dkanzariyaa
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Machine Learning the selfstudy approach
    web_url: https://medium.com/@dkanzariya/machine-learning-a-self-study-approach-50456dba2862
    image_url: https://thumbor.forbes.com/thumbor/960x0/https%3A%2F%2Fspecials-images.forbesimg.com%2Fdam%2Fimageserve%2F966248982%2F960x0.jpg%3Ffit%3Dscale